# Form implementation generated from reading ui file 'comboBox.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(595, 495)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBoxX = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxX.setGeometry(QtCore.QRect(80, 210, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.comboBoxX.setFont(font)
        self.comboBoxX.setObjectName("comboBoxX")
        self.comboBoxX.addItem(" ")
        self.comboBoxX.addItem("")
        self.comboBoxX.addItem("")
        index = self.comboBoxX.findText(" ",QtCore.Qt.MatchFlag.MatchFixedString)
        self.comboBoxX.setCurrentIndex(index)
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(40, 40, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        self.titleLabel.setFont(font)
        self.titleLabel.setMouseTracking(False)
        self.titleLabel.setObjectName("titleLabel")
        self.labelX = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelX.setGeometry(QtCore.QRect(100, 140, 54, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(28)
        font.setBold(True)
        self.labelX.setFont(font)
        self.labelX.setObjectName("labelX")
        self.labelY = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelY.setGeometry(QtCore.QRect(250, 140, 54, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(28)
        font.setBold(True)
        self.labelY.setFont(font)
        self.labelY.setObjectName("labelY")
        self.comboBoxY = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxY.setGeometry(QtCore.QRect(230, 210, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.comboBoxY.setFont(font)
        self.comboBoxY.setObjectName("comboBoxY")
        self.comboBoxY.addItem(" ")
        self.comboBoxY.addItem("")
        self.comboBoxY.addItem("")
        index = self.comboBoxY.findText(" ",QtCore.Qt.MatchFlag.MatchFixedString)
        self.comboBoxY.setCurrentIndex(index)
        self.label_xor = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_xor.setGeometry(QtCore.QRect(410, 140, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(28)
        font.setBold(True)
        self.label_xor.setFont(font)
        self.label_xor.setObjectName("label_xor")
        self.labelResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(410, 210, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        self.labelResult.setFont(font)
        self.labelResult.setMouseTracking(False)
        self.labelResult.setObjectName("labelResult")
        self.answerBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.answerBtn.setGeometry(QtCore.QRect(240, 330, 111, 41))
        self.answerBtn.setObjectName("answerBtn")
        self.answerBtn.clicked.connect(self.findAnswer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 595, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBoxX.setItemText(0, _translate("MainWindow", " "))
        self.comboBoxX.setItemText(1, _translate("MainWindow", "0"))
        self.comboBoxX.setItemText(2, _translate("MainWindow", "1"))
        self.titleLabel.setText(_translate("MainWindow", "XOR Table"))
        self.labelX.setText(_translate("MainWindow", "X"))
        self.labelY.setText(_translate("MainWindow", "Y"))
        self.comboBoxY.setItemText(0, _translate("MainWindow", " "))
        self.comboBoxY.setItemText(1, _translate("MainWindow", "0"))
        self.comboBoxY.setItemText(2, _translate("MainWindow", "1"))
        self.label_xor.setText(_translate("MainWindow", "XOR"))
        self.labelResult.setText(_translate("MainWindow", " "))
        self.answerBtn.setText(_translate("MainWindow", "Answer"))
    
    def findAnswer(self):
        x = self.comboBoxX.currentText()
        y = self.comboBoxY.currentText()
        if x==" " or y==" ":
            self.labelResult.setText(" ")
            return
        
        x,y = int(x),int(y)
        answer = (x and not y) or (y and not x)
        if answer:
            answer = 1
        else:
            answer = 0
        self.labelResult.setText(str(answer))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
