# Form implementation generated from reading ui file 'imageShow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 765)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(parent=self.centralwidget)
        self.image.setGeometry(QtCore.QRect(10, 10, 1111, 621))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("./image/ironman.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.ironmanBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ironmanBtn.setGeometry(QtCore.QRect(170, 660, 211, 51))
        self.ironmanBtn.setObjectName("ironmanBtn")
        self.ironmanBtn.clicked.connect(self.show_ironman)
        self.spidermanBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.spidermanBtn.setGeometry(QtCore.QRect(650, 660, 221, 51))
        self.spidermanBtn.setObjectName("spidermanBtn")
        self.spidermanBtn.clicked.connect(self.show_spiderman)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ironmanBtn.setText(_translate("MainWindow", "iron man"))
        self.spidermanBtn.setText(_translate("MainWindow", "spider man"))

    def show_ironman(self):
        self.image.setPixmap(QtGui.QPixmap("./image/ironman.png"))
    
    def show_spiderman(self):
        self.image.setPixmap(QtGui.QPixmap("./image/spiderman.png"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
