# Form implementation generated from reading ui file 'radioCheckbtn.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 557)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 420, 131, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.print_status)
        self.radioBtn1 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioBtn1.setEnabled(True)
        self.radioBtn1.setGeometry(QtCore.QRect(260, 280, 96, 23))
        self.radioBtn1.setObjectName("radioBtn1")
        self.checkBox1 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox1.setGeometry(QtCore.QRect(270, 330, 82, 23))
        self.checkBox1.setObjectName("checkBox1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "print status"))
        self.radioBtn1.setText(_translate("MainWindow", "radio button"))
        self.checkBox1.setText(_translate("MainWindow", "check box"))
        self.radioBtn1.adjustSize()
        self.checkBox1.adjustSize()

    def print_status(self):
        
        print()
        if self.radioBtn1.isChecked():
            print("radio button is checked")
        else:
            print("radion button un checked")
        
        if self.checkBox1.isChecked():
            print("checkbox is checked")
        else:
            print("checkbox is unchecked")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
